function event(delayMs, commentary, scores) {
  const scoreFields = Array.isArray(scores)
    ? { homeScore: scores[0], awayScore: scores[1] }
    : scores || {};

  return {
    delayMs,
    ...scoreFields,
    commentary,
  };
}

function cricketScore(homeRuns, homeWickets, awayRuns, awayWickets) {
  return {
    homeScore: homeRuns,
    homeWickets,
    awayScore: awayRuns,
    awayWickets,
  };
}

function footballScript({ homeTeam, awayTeam }) {
  const events = [
    event(800, {
      minute: 1,
      sequence: 1,
      period: '1H',
      eventType: 'kickoff',
      message: `Kick-off! ${homeTeam} vs ${awayTeam} is underway in this simulator.`,
      tags: ['kickoff', 'start'],
    }, [0, 0]),
    event(2800, {
      minute: 7,
      sequence: 2,
      period: '1H',
      eventType: 'chance',
      actor: 'Ronaldo',
      team: homeTeam,
      message: `Early warning from ${homeTeam}: Ronaldo peels off the last man but the header is straight at the keeper.`,
      tags: ['chance'],
    }),
    event(3200, {
      minute: 14,
      sequence: 3,
      period: '1H',
      eventType: 'goal',
      actor: 'Ronaldo',
      team: homeTeam,
      message: `GOAL! Cristiano Ronaldo meets a whipped cross and ${homeTeam} lead 1-0!`,
      tags: ['goal'],
      metadata: { homeScore: 1, awayScore: 0 },
    }, [1, 0]),
    event(2600, {
      minute: 22,
      sequence: 4,
      period: '1H',
      eventType: 'save',
      actor: 'Martinez',
      team: awayTeam,
      message: `${awayTeam} hit back immediately. Martinez produces a huge save from a low drive at the near post.`,
      tags: ['save'],
    }),
    event(3000, {
      minute: 31,
      sequence: 5,
      period: '1H',
      eventType: 'yellow_card',
      actor: 'Fernandes',
      team: homeTeam,
      message: `Yellow card. Fernandes clips the heels of an ${awayTeam} midfielder on the counter.`,
      tags: ['card', 'yellow'],
    }),
    event(2800, {
      minute: 38,
      sequence: 6,
      period: '1H',
      eventType: 'goal',
      actor: 'Messi',
      team: awayTeam,
      message: `GOAL! Lionel Messi curls one into the far corner. ${awayTeam} are level at 1-1!`,
      tags: ['goal'],
      metadata: { homeScore: 1, awayScore: 1 },
    }, [1, 1]),
    event(2400, {
      minute: 45,
      sequence: 7,
      period: 'HT',
      eventType: 'half_time',
      message: `Half-time. ${homeTeam} 1-1 ${awayTeam}. Plenty still to play for.`,
      tags: ['half-time'],
    }),
    event(2200, {
      minute: 46,
      sequence: 8,
      period: '2H',
      eventType: 'kickoff',
      message: `Second half underway. ${awayTeam} restart.`,
      tags: ['kickoff'],
    }),
    event(3000, {
      minute: 54,
      sequence: 9,
      period: '2H',
      eventType: 'chance',
      actor: 'Rafael Leao',
      team: homeTeam,
      message: `Leao burns down the left and cuts inside, but the shot is blocked.`,
      tags: ['chance'],
    }),
    event(3200, {
      minute: 63,
      sequence: 10,
      period: '2H',
      eventType: 'goal',
      actor: 'Alvarez',
      team: awayTeam,
      message: `GOAL! Alvarez finishes a flowing ${awayTeam} move. 1-2, and the visitors lead!`,
      tags: ['goal'],
      metadata: { homeScore: 1, awayScore: 2 },
    }, [1, 2]),
    event(2800, {
      minute: 71,
      sequence: 11,
      period: '2H',
      eventType: 'substitution',
      actor: 'Ramos',
      team: homeTeam,
      message: `${homeTeam} throw on Ramos. They need a response.`,
      tags: ['substitution'],
    }),
    event(3000, {
      minute: 78,
      sequence: 12,
      period: '2H',
      eventType: 'goal',
      actor: 'Ramos',
      team: homeTeam,
      message: `GOAL! Ramos with a towering header! ${homeTeam} 2-2 ${awayTeam}!`,
      tags: ['goal'],
      metadata: { homeScore: 2, awayScore: 2 },
    }, [2, 2]),
    event(2600, {
      minute: 85,
      sequence: 13,
      period: '2H',
      eventType: 'chance',
      actor: 'Messi',
      team: awayTeam,
      message: `Messi drops a shoulder and shoots... just wide of the post. Hearts in mouths.`,
      tags: ['chance'],
    }),
    event(2800, {
      minute: 90,
      sequence: 14,
      period: '2H',
      eventType: 'added_time',
      message: `Four minutes of added time. Still 2-2.`,
      tags: ['stoppage'],
    }),
    event(3200, {
      minute: 90,
      sequence: 15,
      period: 'FT',
      eventType: 'full_time',
      message: `Full-time! ${homeTeam} 2-2 ${awayTeam}. A thriller from start to finish.`,
      tags: ['full-time', 'end'],
      metadata: { homeScore: 2, awayScore: 2 },
    }, [2, 2]),
  ];

  return { sport: 'football', events };
}

function cricketScript({ homeTeam, awayTeam }) {
  const events = [
    event(800, {
      minute: 0,
      sequence: 1,
      period: 'INN1',
      eventType: 'toss',
      message: `Toss done. ${homeTeam} bat first against ${awayTeam} in this T20 simulator.`,
      tags: ['toss', 'start'],
      metadata: { homeScoreLabel: '0/0', awayScoreLabel: '0/0' },
    }, cricketScore(0, 0, 0, 0)),
    event(2500, {
      minute: 1,
      sequence: 2,
      period: 'INN1',
      eventType: 'four',
      actor: 'Rohit Sharma',
      team: homeTeam,
      message: `FOUR! Rohit punches through cover. ${homeTeam} 4/0.`,
      tags: ['boundary', 'four'],
      metadata: { homeScoreLabel: '4/0', awayScoreLabel: '0/0' },
    }, cricketScore(4, 0, 0, 0)),
    event(2400, {
      minute: 2,
      sequence: 3,
      period: 'INN1',
      eventType: 'wicket',
      actor: 'Rohit Sharma',
      team: homeTeam,
      message: `WICKET! Rohit nicks off. ${homeTeam} 8/1.`,
      tags: ['wicket'],
      metadata: { homeScoreLabel: '8/1', awayScoreLabel: '0/0' },
    }, cricketScore(8, 1, 0, 0)),
    event(2600, {
      minute: 3,
      sequence: 4,
      period: 'INN1',
      eventType: 'wicket',
      actor: 'Shubman Gill',
      team: homeTeam,
      message: `WICKET! Gill is beaten by a yorker. ${homeTeam} 18/2 after 3.`,
      tags: ['wicket'],
      metadata: { homeScoreLabel: '18/2', awayScoreLabel: '0/0' },
    }, cricketScore(18, 2, 0, 0)),
    event(2800, {
      minute: 7,
      sequence: 5,
      period: 'INN1',
      eventType: 'wicket',
      actor: 'Axar Patel',
      team: homeTeam,
      message: `WICKET! Axar holes out. ${homeTeam} 50/3.`,
      tags: ['wicket'],
      metadata: { homeScoreLabel: '50/3', awayScoreLabel: '0/0' },
    }, cricketScore(50, 3, 0, 0)),
    event(2800, {
      minute: 10,
      sequence: 6,
      period: 'INN1',
      eventType: 'milestone',
      actor: 'Virat Kohli',
      team: homeTeam,
      message: `Fifty for Kohli! ${homeTeam} racing at 78/3 after 10 overs.`,
      tags: ['fifty'],
      metadata: { homeScoreLabel: '78/3', awayScoreLabel: '0/0' },
    }, cricketScore(78, 3, 0, 0)),
    event(2600, {
      minute: 14,
      sequence: 7,
      period: 'INN1',
      eventType: 'six',
      actor: 'Suryakumar Yadav',
      team: homeTeam,
      message: `SIX more from SKY over extra cover. ${homeTeam} 121/3.`,
      tags: ['boundary', 'six'],
      metadata: { homeScoreLabel: '121/3', awayScoreLabel: '0/0' },
    }, cricketScore(121, 3, 0, 0)),
    event(2500, {
      minute: 18,
      sequence: 8,
      period: 'INN1',
      eventType: 'wicket',
      actor: 'Virat Kohli',
      team: homeTeam,
      message: `Caught in the deep! Kohli goes for 72. ${homeTeam} 158/4 with two overs left.`,
      tags: ['wicket'],
      metadata: { homeScoreLabel: '158/4', awayScoreLabel: '0/0' },
    }, cricketScore(158, 4, 0, 0)),
    event(2800, {
      minute: 20,
      sequence: 9,
      period: 'INN1',
      eventType: 'innings_end',
      actor: 'Hardik Pandya',
      team: homeTeam,
      message: `${homeTeam} finish on 186/4. ${awayTeam} need 187 to win.`,
      tags: ['innings'],
      metadata: { homeScoreLabel: '186/4', awayScoreLabel: '0/0' },
    }, cricketScore(186, 4, 0, 0)),
    event(2200, {
      minute: 0,
      sequence: 10,
      period: 'INN2',
      eventType: 'innings_start',
      message: `${awayTeam} open the chase. 187 required from 120 balls.`,
      tags: ['start'],
      metadata: { homeScoreLabel: '186/4', awayScoreLabel: '0/0' },
    }, cricketScore(186, 4, 0, 0)),
    event(2600, {
      minute: 4,
      sequence: 11,
      period: 'INN2',
      eventType: 'four',
      actor: 'Head',
      team: awayTeam,
      message: `FOUR! Head slashes over point. ${awayTeam} 36/0 after 4.`,
      tags: ['boundary', 'four'],
      metadata: { homeScoreLabel: '186/4', awayScoreLabel: '36/0' },
    }, cricketScore(186, 4, 36, 0)),
    event(2600, {
      minute: 8,
      sequence: 12,
      period: 'INN2',
      eventType: 'wicket',
      actor: 'Warner',
      team: awayTeam,
      message: `BOWLED HIM! Warner misses a yorker. ${awayTeam} 61/2.`,
      tags: ['wicket'],
      metadata: { homeScoreLabel: '186/4', awayScoreLabel: '61/2' },
    }, cricketScore(186, 4, 61, 2)),
    event(2800, {
      minute: 12,
      sequence: 13,
      period: 'INN2',
      eventType: 'six',
      actor: 'Maxwell',
      team: awayTeam,
      message: `Maxwell launches a huge six. ${awayTeam} 102/3, rate climbing.`,
      tags: ['boundary', 'six'],
      metadata: { homeScoreLabel: '186/4', awayScoreLabel: '102/3' },
    }, cricketScore(186, 4, 102, 3)),
    event(2600, {
      minute: 16,
      sequence: 14,
      period: 'INN2',
      eventType: 'wicket',
      actor: 'Maxwell',
      team: awayTeam,
      message: `Caught at long-off! Maxwell gone. ${awayTeam} 138/6. 49 needed off 24.`,
      tags: ['wicket'],
      metadata: { homeScoreLabel: '186/4', awayScoreLabel: '138/6' },
    }, cricketScore(186, 4, 138, 6)),
    event(2800, {
      minute: 19,
      sequence: 15,
      period: 'INN2',
      eventType: 'wicket',
      actor: 'Cummins',
      team: awayTeam,
      message: `Another one! Cummins holes out. ${awayTeam} 165/8. 22 needed off the last over.`,
      tags: ['wicket'],
      metadata: { homeScoreLabel: '186/4', awayScoreLabel: '165/8' },
    }, cricketScore(186, 4, 165, 8)),
    event(3200, {
      minute: 20,
      sequence: 16,
      period: 'FT',
      eventType: 'match_end',
      message: `All over! ${homeTeam} win by 14 runs. Final: ${homeTeam} 186/4, ${awayTeam} 172/8.`,
      tags: ['end', 'result'],
      metadata: { homeScoreLabel: '186/4', awayScoreLabel: '172/8' },
    }, cricketScore(186, 4, 172, 8)),
  ];

  return { sport: 'cricket', events };
}

function hockeyScript({ homeTeam, awayTeam }) {
  const events = [
    event(800, {
      minute: 1,
      sequence: 1,
      period: '1P',
      eventType: 'bully_off',
      message: `Bully-off! ${homeTeam} vs ${awayTeam} in this hockey simulator.`,
      tags: ['start'],
    }, [0, 0]),
    event(2600, {
      minute: 6,
      sequence: 2,
      period: '1P',
      eventType: 'penalty_corner',
      team: homeTeam,
      message: `Penalty corner to ${homeTeam} after a foot on the line.`,
      tags: ['pc'],
    }),
    event(2800, {
      minute: 7,
      sequence: 3,
      period: '1P',
      eventType: 'goal',
      actor: 'Harmanpreet Singh',
      team: homeTeam,
      message: `GOAL! Harmanpreet slams the drag-flick home. ${homeTeam} 1-0!`,
      tags: ['goal', 'pc'],
      metadata: { homeScore: 1, awayScore: 0 },
    }, [1, 0]),
    event(2500, {
      minute: 14,
      sequence: 4,
      period: '1P',
      eventType: 'save',
      actor: 'PR Sreejesh',
      team: homeTeam,
      message: `Sreejesh with a pad save from a close-range deflection.`,
      tags: ['save'],
    }),
    event(2400, {
      minute: 20,
      sequence: 5,
      period: '1P',
      eventType: 'period_end',
      message: `End of Q1. ${homeTeam} 1-0 ${awayTeam}.`,
      tags: ['period'],
    }),
    event(2200, {
      minute: 22,
      sequence: 6,
      period: '2P',
      eventType: 'goal',
      actor: 'Ammad Butt',
      team: awayTeam,
      message: `GOAL! ${awayTeam} equalise from a swift counter. 1-1!`,
      tags: ['goal'],
      metadata: { homeScore: 1, awayScore: 1 },
    }, [1, 1]),
    event(2800, {
      minute: 31,
      sequence: 7,
      period: '2P',
      eventType: 'green_card',
      actor: 'Mubashar',
      team: awayTeam,
      message: `Green card. ${awayTeam} down a man for two minutes.`,
      tags: ['card'],
    }),
    event(3000, {
      minute: 34,
      sequence: 8,
      period: '2P',
      eventType: 'goal',
      actor: 'Abhishek',
      team: homeTeam,
      message: `GOAL! Abhishek finishes a rebound. ${homeTeam} lead 2-1 at half.`,
      tags: ['goal'],
      metadata: { homeScore: 2, awayScore: 1 },
    }, [2, 1]),
    event(2200, {
      minute: 40,
      sequence: 9,
      period: 'HT',
      eventType: 'half_time',
      message: `Half-time. ${homeTeam} 2-1 ${awayTeam}.`,
      tags: ['half-time'],
    }),
    event(2400, {
      minute: 42,
      sequence: 10,
      period: '3P',
      eventType: 'penalty_corner',
      team: awayTeam,
      message: `${awayTeam} earn a penalty corner after a desperate tackle.`,
      tags: ['pc'],
    }),
    event(2800, {
      minute: 43,
      sequence: 11,
      period: '3P',
      eventType: 'goal',
      actor: 'Razzaq',
      team: awayTeam,
      message: `GOAL! Razzaq's flick sneaks in at the far post. 2-2!`,
      tags: ['goal', 'pc'],
      metadata: { homeScore: 2, awayScore: 2 },
    }, [2, 2]),
    event(2600, {
      minute: 52,
      sequence: 12,
      period: '3P',
      eventType: 'chance',
      actor: 'Mandeep Singh',
      team: homeTeam,
      message: `Mandeep is denied by the post. Still 2-2.`,
      tags: ['chance'],
    }),
    event(2400, {
      minute: 60,
      sequence: 13,
      period: '4P',
      eventType: 'period_start',
      message: `Final quarter. Winner-takes-all atmosphere.`,
      tags: ['period'],
    }),
    event(3000, {
      minute: 67,
      sequence: 14,
      period: '4P',
      eventType: 'goal',
      actor: 'Harmanpreet Singh',
      team: homeTeam,
      message: `GOAL! Captain Harmanpreet again from another PC. ${homeTeam} 3-2!`,
      tags: ['goal', 'pc'],
      metadata: { homeScore: 3, awayScore: 2 },
    }, [3, 2]),
    event(3200, {
      minute: 70,
      sequence: 15,
      period: 'FT',
      eventType: 'full_time',
      message: `Final hooter! ${homeTeam} beat ${awayTeam} 3-2 in a classic.`,
      tags: ['end', 'full-time'],
      metadata: { homeScore: 3, awayScore: 2 },
    }, [3, 2]),
  ];

  return { sport: 'hockey', events };
}

const BUILDERS = {
  football: footballScript,
  cricket: cricketScript,
  hockey: hockeyScript,
};

export function getSimulatorScript(match) {
  const sport = String(match.sport || '').trim().toLowerCase();
  const builder = BUILDERS[sport];
  if (!builder) {
    return null;
  }

  const script = builder(match);
  const estimatedDurationMs = script.events.reduce((sum, item) => sum + item.delayMs, 0);
  return { ...script, estimatedDurationMs };
}

export const SIMULATOR_SPORTS = Object.keys(BUILDERS);
